# Generated by Django 2.1 on 2019-10-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='PantryItem',
        ),
    ]
